### ISSUE TITLE
Build checks broken: edgedrivers < v100 no longer hosted

### ISSUE THREAD

**Issue by treyturner** [webdriverextensions/webdriverextensions-maven-plugin-repository#119]
[Build checks are broken](https://github.com/webdriverextensions/webdriverextensions-maven-plugin-repository/actions/runs/9918857257/job/27404043191#step:5:5771) because MS has delisted edgedriver < v100.

I can delete the offending entries, but this might break builds that haven't been touched in a long time as mentioned in #93 

This blocks #118 in the meantime.

**Comment by sephiroth-j** [comment]
> I can delete the offending entries, but this might break builds that haven't been touched in a long time as mentioned in https://github.com/webdriverextensions/webdriverextensions-maven-plugin-repository/issues/93

But these builds are already broken because the drivers can not be downloaded anymore.

I don't know what we can do about it. So there's only one thing to do: delete the offending entries too.
